
openapi: 3.0.0
info:
  title: Inforst Game API
  description: REST API backend for Inforst - A Journey of Legends and Balance
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: Local development server

paths:
  /auth/register:
    post:
      summary: Register a new player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterInput'
      responses:
        201:
          description: Player registered successfully

  /auth/login:
    post:
      summary: Login a player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        200:
          description: Login successful

components:
  schemas:
    RegisterInput:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
      required:
        - username
        - password
        - email

    LoginInput:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password